## This notebook is written in the R programming language in Jupyter

In [3]:
print('hello world')

[1] "hello world"


## Hello World

ERROR: Error in input("How different is R and python"): could not find function "input"


## Vectors

In [3]:
x = 1:10
x

[1]  1  2  3  4  5  6  7  8  9 10

In [4]:
class(x)

[1] "integer"

In [7]:
names(x) = letters[1:10]

In [10]:
x[1:3]

a b c 
1 2 3

In [11]:
x[c("a","b")]

a b 
1 2

In [12]:
x = 1:3

In [13]:
names(x) = c("a", "a", "b")
x

a a b 
1 2 3

In [14]:
x["a"]

a 
1

In [15]:
#find dupliicates
anyDuplicated(names(x))

[1] 2

In [16]:
names(x)

[1] "a" "a" "b"

In [17]:
names(x) = letters[1:3]

In [18]:
anyDuplicated(names(x))

[1] 0

In [19]:
x

a b c 
1 2 3

In [20]:
names(x)

[1] "a" "b" "c"

In [21]:
x = 1 #note that when you assign a number this way it is numeric
class(x)

[1] "numeric"

In [22]:
x = 1:3
class(x)

[1] "integer"

In [23]:
x = 1L #if you want it to be an integer you need to add a L after it
class(x)

[1] "integer"

In [26]:
x

[1] 1

In [27]:
.Machine$integer.max #This is how big an integer can be (integermax)

[1] 2147483647

In [28]:
2^31 -1 == .Machine$integer.max

[1] TRUE

In [30]:
round(.Machine$integer.max/10^6)

[1] 2147

Note that this max limit is about the size of the genome, so you may end up running into limits... 

## Matrices

In [41]:
x = matrix(1:9, ncol = 3, nrow = 3)
x

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [49]:
dim(x) #dimensions

[1] 3 3

In [50]:
ncol(x)

[1] 3

In [51]:
nrow(x)

[1] 3

In [52]:
x[1:2,]

[,1] [,2] [,3]
a 1    4    7   
b 2    5    8

In [53]:
x[1:2,1:2]

[,1] [,2]
a 1    4   
b 2    5

In [55]:
rownames(x) = letters[1:3]

In [56]:
x["a",]

[1] 1 4 7

In [57]:
x[x>5] #give all elements of matrix greater than 5

[1] 6 7 8 9

In [58]:
x = matrix(1:9, ncol = 3, nrow = 3, byrow=TRUE)

In [59]:
x

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [61]:
x = list(a = rnorm(3), b = letters[1:5], matrix)
x

$a
[1] -1.0994243  1.1539222  0.2309188

$b
[1] "a" "b" "c" "d" "e"

[[3]]
function (data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL) 
{
    if (is.object(data) || !is.atomic(data)) 
        data <- as.vector(data)
    .Internal(matrix(data, nrow, ncol, byrow, dimnames, missing(nrow), 
        missing(ncol)))
}
<bytecode: 0x00000000618634d0>
<environment: namespace:base>

In [63]:
x[1:2]

$a
[1] -1.0994243  1.1539222  0.2309188

$b
[1] "a" "b" "c" "d" "e"

In [64]:
x[1]

$a
[1] -1.0994243  1.1539222  0.2309188

In [65]:
x["a"]

$a
[1] -1.0994243  1.1539222  0.2309188

In [66]:
x$a

[1] -1.0994243  1.1539222  0.2309188

In [67]:
names(x) = c("a", "letters", "c")

In [68]:
x$letters

[1] "a" "b" "c" "d" "e"

In [69]:
x$let #be careful with this if you have similar names

[1] "a" "b" "c" "d" "e"

In [71]:
names(x) = c("a", "letters", "letters2")
x$let #now it won't work...

NULL

In [72]:
x["letters"]

$letters
[1] "a" "b" "c" "d" "e"

In [73]:
x$letters

[1] "a" "b" "c" "d" "e"

In [75]:
as.list(1:3)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

In [76]:
x = list(rnorm(3), 3:9)
x

[[1]]
[1] 0.5935733 1.0638881 0.1609246

[[2]]
[1] 3 4 5 6 7 8 9

In [77]:
lapply(x, mean) #take the list and apply some function to it (mean)

[[1]]
[1] 0.6061286

[[2]]
[1] 6

In [78]:
unlist(lapply(x, mean)) #makes it a vector instead of list

[1] 0.6061286 6.0000000

In [ ]:
sapply(x, mean) #simplify apply makes everything a number or vector of same length

## Dataframes

In [79]:
x <- data.frame(sex = c("M", "M", "F"), age = c(32, 34, 29)) 

In [80]:
x

sex age
1 M   32 
2 M   34 
3 F   29

In [81]:
x$sex

[1] M M F
Levels: F M

In [82]:
x[["sex"]]

[1] M M F
Levels: F M

In [84]:
x[1, "sex"]

[1] M
Levels: F M

In [85]:
x

sex age
1 M   32 
2 M   34 
3 F   29

In [87]:
sapply(x, class) #figure out what class everything in the dataframe is

sex       age 
 "factor" "numeric"

In [88]:
as.matrix(x)

sex age
[1,] M   32 
[2,] M   34 
[3,] F   29

In [89]:
as.list(x)

$sex
[1] M M F
Levels: F M

$age
[1] 32 34 29

In [90]:
library(methods)
as(x, "matrix")

sex age
[1,] M   32 
[2,] M   34 
[3,] F   29